<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TPembayaran', 'doctrine');

/**
 * BaseTPembayaran
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $kode_pembayaran
 * @property integer $kode_pemesanan
 * @property integer $kode_cara_bayar
 * @property date $tanggal_pembayaran
 * @property integer $amount
 * @property string $no_referensi
 * @property integer $approval_kasir
 * @property timestamp $tanggal_approval_kasir
 * @property integer $approval_manager_penjualan
 * @property date $tanggal_approval_manager
 * 
 * @method integer     getKodePembayaran()             Returns the current record's "kode_pembayaran" value
 * @method integer     getKodePemesanan()              Returns the current record's "kode_pemesanan" value
 * @method integer     getKodeCaraBayar()              Returns the current record's "kode_cara_bayar" value
 * @method date        getTanggalPembayaran()          Returns the current record's "tanggal_pembayaran" value
 * @method integer     getAmount()                     Returns the current record's "amount" value
 * @method string      getNoReferensi()                Returns the current record's "no_referensi" value
 * @method integer     getApprovalKasir()              Returns the current record's "approval_kasir" value
 * @method timestamp   getTanggalApprovalKasir()       Returns the current record's "tanggal_approval_kasir" value
 * @method integer     getApprovalManagerPenjualan()   Returns the current record's "approval_manager_penjualan" value
 * @method date        getTanggalApprovalManager()     Returns the current record's "tanggal_approval_manager" value
 * @method TPembayaran setKodePembayaran()             Sets the current record's "kode_pembayaran" value
 * @method TPembayaran setKodePemesanan()              Sets the current record's "kode_pemesanan" value
 * @method TPembayaran setKodeCaraBayar()              Sets the current record's "kode_cara_bayar" value
 * @method TPembayaran setTanggalPembayaran()          Sets the current record's "tanggal_pembayaran" value
 * @method TPembayaran setAmount()                     Sets the current record's "amount" value
 * @method TPembayaran setNoReferensi()                Sets the current record's "no_referensi" value
 * @method TPembayaran setApprovalKasir()              Sets the current record's "approval_kasir" value
 * @method TPembayaran setTanggalApprovalKasir()       Sets the current record's "tanggal_approval_kasir" value
 * @method TPembayaran setApprovalManagerPenjualan()   Sets the current record's "approval_manager_penjualan" value
 * @method TPembayaran setTanggalApprovalManager()     Sets the current record's "tanggal_approval_manager" value
 * 
 * @package    properti
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTPembayaran extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_pembayaran');
        $this->hasColumn('kode_pembayaran', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('kode_pemesanan', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('kode_cara_bayar', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tanggal_pembayaran', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('amount', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('no_referensi', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('approval_kasir', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tanggal_approval_kasir', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('approval_manager_penjualan', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('tanggal_approval_manager', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}