<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RStatusPesanan', 'doctrine');

/**
 * BaseRStatusPesanan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $kode_status_pesanan
 * @property string $status_pesanan
 * 
 * @method integer        getKodeStatusPesanan()   Returns the current record's "kode_status_pesanan" value
 * @method string         getStatusPesanan()       Returns the current record's "status_pesanan" value
 * @method RStatusPesanan setKodeStatusPesanan()   Sets the current record's "kode_status_pesanan" value
 * @method RStatusPesanan setStatusPesanan()       Sets the current record's "status_pesanan" value
 * 
 * @package    properti
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRStatusPesanan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('r_status_pesanan');
        $this->hasColumn('kode_status_pesanan', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('status_pesanan', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}