<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TProyek', 'doctrine');

/**
 * BaseTProyek
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $kode_proyek
 * @property string $nama_proyek
 * @property integer $jenis_proyek
 * @property string $nama_jalan
 * @property integer $kode_kelurahan
 * @property integer $kode_kecamatan
 * @property integer $kode_kabupaten_kota
 * @property string $kode_pos
 * @property integer $kode_propinsi
 * 
 * @method string  getKodeProyek()          Returns the current record's "kode_proyek" value
 * @method string  getNamaProyek()          Returns the current record's "nama_proyek" value
 * @method integer getJenisProyek()         Returns the current record's "jenis_proyek" value
 * @method string  getNamaJalan()           Returns the current record's "nama_jalan" value
 * @method integer getKodeKelurahan()       Returns the current record's "kode_kelurahan" value
 * @method integer getKodeKecamatan()       Returns the current record's "kode_kecamatan" value
 * @method integer getKodeKabupatenKota()   Returns the current record's "kode_kabupaten_kota" value
 * @method string  getKodePos()             Returns the current record's "kode_pos" value
 * @method integer getKodePropinsi()        Returns the current record's "kode_propinsi" value
 * @method TProyek setKodeProyek()          Sets the current record's "kode_proyek" value
 * @method TProyek setNamaProyek()          Sets the current record's "nama_proyek" value
 * @method TProyek setJenisProyek()         Sets the current record's "jenis_proyek" value
 * @method TProyek setNamaJalan()           Sets the current record's "nama_jalan" value
 * @method TProyek setKodeKelurahan()       Sets the current record's "kode_kelurahan" value
 * @method TProyek setKodeKecamatan()       Sets the current record's "kode_kecamatan" value
 * @method TProyek setKodeKabupatenKota()   Sets the current record's "kode_kabupaten_kota" value
 * @method TProyek setKodePos()             Sets the current record's "kode_pos" value
 * @method TProyek setKodePropinsi()        Sets the current record's "kode_propinsi" value
 * 
 * @package    properti
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTProyek extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_proyek');
        $this->hasColumn('kode_proyek', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('nama_proyek', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('jenis_proyek', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nama_jalan', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('kode_kelurahan', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('kode_kecamatan', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('kode_kabupaten_kota', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('kode_pos', 'string', 5, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 5,
             ));
        $this->hasColumn('kode_propinsi', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}