<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RCaraBayar', 'doctrine');

/**
 * BaseRCaraBayar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $kode_cara_bayar
 * @property string $cara_bayar
 * 
 * @method integer    getKodeCaraBayar()   Returns the current record's "kode_cara_bayar" value
 * @method string     getCaraBayar()       Returns the current record's "cara_bayar" value
 * @method RCaraBayar setKodeCaraBayar()   Sets the current record's "kode_cara_bayar" value
 * @method RCaraBayar setCaraBayar()       Sets the current record's "cara_bayar" value
 * 
 * @package    properti
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRCaraBayar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('r_cara_bayar');
        $this->hasColumn('kode_cara_bayar', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('cara_bayar', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}