<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TSales', 'doctrine');

/**
 * BaseTSales
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $kode_sales
 * @property string $nama_sales
 * @property integer $kode_unit_sales
 * @property integer $kode_atasan
 * 
 * @method integer getKodeSales()       Returns the current record's "kode_sales" value
 * @method string  getNamaSales()       Returns the current record's "nama_sales" value
 * @method integer getKodeUnitSales()   Returns the current record's "kode_unit_sales" value
 * @method integer getKodeAtasan()      Returns the current record's "kode_atasan" value
 * @method TSales  setKodeSales()       Sets the current record's "kode_sales" value
 * @method TSales  setNamaSales()       Sets the current record's "nama_sales" value
 * @method TSales  setKodeUnitSales()   Sets the current record's "kode_unit_sales" value
 * @method TSales  setKodeAtasan()      Sets the current record's "kode_atasan" value
 * 
 * @package    properti
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTSales extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_sales');
        $this->hasColumn('kode_sales', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nama_sales', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('kode_unit_sales', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('kode_atasan', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}