<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TKonsumen', 'doctrine');

/**
 * BaseTKonsumen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $kode_status_konsumen
 * @property integer $kode_konsumen
 * @property string $nama_lengkap_konsumen
 * @property string $tempat_lahir_konsumen
 * @property date $tanggal_lahir_konsumen
 * @property string $kode_jenis_kelamin
 * @property integer $kode_identitas
 * @property string $no_identitas
 * @property string $nama_jalan
 * @property string $rt
 * @property string $rw
 * @property integer $kode_kelurahan
 * @property integer $kode_kecamatan
 * @property integer $kode_kabupaten
 * @property string $kode_pos
 * @property integer $kode_propinsi
 * @property string $kode_area
 * @property string $telpon_rumah
 * @property string $no_hp
 * @property string $no_hp2
 * @property string $email1
 * @property string $email2
 * @property integer $kode_pekerjaan
 * 
 * @method integer   getKodeStatusKonsumen()     Returns the current record's "kode_status_konsumen" value
 * @method integer   getKodeKonsumen()           Returns the current record's "kode_konsumen" value
 * @method string    getNamaLengkapKonsumen()    Returns the current record's "nama_lengkap_konsumen" value
 * @method string    getTempatLahirKonsumen()    Returns the current record's "tempat_lahir_konsumen" value
 * @method date      getTanggalLahirKonsumen()   Returns the current record's "tanggal_lahir_konsumen" value
 * @method string    getKodeJenisKelamin()       Returns the current record's "kode_jenis_kelamin" value
 * @method integer   getKodeIdentitas()          Returns the current record's "kode_identitas" value
 * @method string    getNoIdentitas()            Returns the current record's "no_identitas" value
 * @method string    getNamaJalan()              Returns the current record's "nama_jalan" value
 * @method string    getRt()                     Returns the current record's "rt" value
 * @method string    getRw()                     Returns the current record's "rw" value
 * @method integer   getKodeKelurahan()          Returns the current record's "kode_kelurahan" value
 * @method integer   getKodeKecamatan()          Returns the current record's "kode_kecamatan" value
 * @method integer   getKodeKabupaten()          Returns the current record's "kode_kabupaten" value
 * @method string    getKodePos()                Returns the current record's "kode_pos" value
 * @method integer   getKodePropinsi()           Returns the current record's "kode_propinsi" value
 * @method string    getKodeArea()               Returns the current record's "kode_area" value
 * @method string    getTelponRumah()            Returns the current record's "telpon_rumah" value
 * @method string    getNoHp()                   Returns the current record's "no_hp" value
 * @method string    getNoHp2()                  Returns the current record's "no_hp2" value
 * @method string    getEmail1()                 Returns the current record's "email1" value
 * @method string    getEmail2()                 Returns the current record's "email2" value
 * @method integer   getKodePekerjaan()          Returns the current record's "kode_pekerjaan" value
 * @method TKonsumen setKodeStatusKonsumen()     Sets the current record's "kode_status_konsumen" value
 * @method TKonsumen setKodeKonsumen()           Sets the current record's "kode_konsumen" value
 * @method TKonsumen setNamaLengkapKonsumen()    Sets the current record's "nama_lengkap_konsumen" value
 * @method TKonsumen setTempatLahirKonsumen()    Sets the current record's "tempat_lahir_konsumen" value
 * @method TKonsumen setTanggalLahirKonsumen()   Sets the current record's "tanggal_lahir_konsumen" value
 * @method TKonsumen setKodeJenisKelamin()       Sets the current record's "kode_jenis_kelamin" value
 * @method TKonsumen setKodeIdentitas()          Sets the current record's "kode_identitas" value
 * @method TKonsumen setNoIdentitas()            Sets the current record's "no_identitas" value
 * @method TKonsumen setNamaJalan()              Sets the current record's "nama_jalan" value
 * @method TKonsumen setRt()                     Sets the current record's "rt" value
 * @method TKonsumen setRw()                     Sets the current record's "rw" value
 * @method TKonsumen setKodeKelurahan()          Sets the current record's "kode_kelurahan" value
 * @method TKonsumen setKodeKecamatan()          Sets the current record's "kode_kecamatan" value
 * @method TKonsumen setKodeKabupaten()          Sets the current record's "kode_kabupaten" value
 * @method TKonsumen setKodePos()                Sets the current record's "kode_pos" value
 * @method TKonsumen setKodePropinsi()           Sets the current record's "kode_propinsi" value
 * @method TKonsumen setKodeArea()               Sets the current record's "kode_area" value
 * @method TKonsumen setTelponRumah()            Sets the current record's "telpon_rumah" value
 * @method TKonsumen setNoHp()                   Sets the current record's "no_hp" value
 * @method TKonsumen setNoHp2()                  Sets the current record's "no_hp2" value
 * @method TKonsumen setEmail1()                 Sets the current record's "email1" value
 * @method TKonsumen setEmail2()                 Sets the current record's "email2" value
 * @method TKonsumen setKodePekerjaan()          Sets the current record's "kode_pekerjaan" value
 * 
 * @package    properti
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTKonsumen extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_konsumen');
        $this->hasColumn('kode_status_konsumen', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('kode_konsumen', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nama_lengkap_konsumen', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('tempat_lahir_konsumen', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('tanggal_lahir_konsumen', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('kode_jenis_kelamin', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('kode_identitas', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('no_identitas', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('nama_jalan', 'string', 35, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 35,
             ));
        $this->hasColumn('rt', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('rw', 'string', 3, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 3,
             ));
        $this->hasColumn('kode_kelurahan', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('kode_kecamatan', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('kode_kabupaten', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('kode_pos', 'string', 5, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 5,
             ));
        $this->hasColumn('kode_propinsi', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('kode_area', 'string', 4, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('telpon_rumah', 'string', 8, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('no_hp', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('no_hp2', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('email1', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('email2', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
        $this->hasColumn('kode_pekerjaan', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}