<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RStatusKonsumen', 'doctrine');

/**
 * BaseRStatusKonsumen
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $kode_status_konsumen
 * @property string $status_konsumen
 * 
 * @method integer         getKodeStatusKonsumen()   Returns the current record's "kode_status_konsumen" value
 * @method string          getStatusKonsumen()       Returns the current record's "status_konsumen" value
 * @method RStatusKonsumen setKodeStatusKonsumen()   Sets the current record's "kode_status_konsumen" value
 * @method RStatusKonsumen setStatusKonsumen()       Sets the current record's "status_konsumen" value
 * 
 * @package    properti
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRStatusKonsumen extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('r_status_konsumen');
        $this->hasColumn('kode_status_konsumen', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('status_konsumen', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}