<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TFasilitas', 'doctrine');

/**
 * BaseTFasilitas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $kode_proyek
 * @property integer $kode_fasilitas
 * 
 * @method integer    getId()             Returns the current record's "id" value
 * @method integer    getKodeProyek()     Returns the current record's "kode_proyek" value
 * @method integer    getKodeFasilitas()  Returns the current record's "kode_fasilitas" value
 * @method TFasilitas setId()             Sets the current record's "id" value
 * @method TFasilitas setKodeProyek()     Sets the current record's "kode_proyek" value
 * @method TFasilitas setKodeFasilitas()  Sets the current record's "kode_fasilitas" value
 * 
 * @package    properti
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTFasilitas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_fasilitas');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('kode_proyek', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('kode_fasilitas', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}