<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('THarga', 'doctrine');

/**
 * BaseTHarga
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $kode_proyek
 * @property string $kode_tower
 * @property integer $type_unit
 * @property integer $harga_unit
 * @property date $berlaku_mulai
 * 
 * @method integer getId()            Returns the current record's "id" value
 * @method string  getKodeProyek()    Returns the current record's "kode_proyek" value
 * @method string  getKodeTower()     Returns the current record's "kode_tower" value
 * @method integer getTypeUnit()      Returns the current record's "type_unit" value
 * @method integer getHargaUnit()     Returns the current record's "harga_unit" value
 * @method date    getBerlakuMulai()  Returns the current record's "berlaku_mulai" value
 * @method THarga  setId()            Sets the current record's "id" value
 * @method THarga  setKodeProyek()    Sets the current record's "kode_proyek" value
 * @method THarga  setKodeTower()     Sets the current record's "kode_tower" value
 * @method THarga  setTypeUnit()      Sets the current record's "type_unit" value
 * @method THarga  setHargaUnit()     Sets the current record's "harga_unit" value
 * @method THarga  setBerlakuMulai()  Sets the current record's "berlaku_mulai" value
 * 
 * @package    properti
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTHarga extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_harga');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('kode_proyek', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('kode_tower', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('type_unit', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('harga_unit', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('berlaku_mulai', 'date', 25, array(
             'type' => 'date',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}