<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RJenisUnit', 'doctrine');

/**
 * BaseRJenisUnit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $kode_jenis_unit
 * @property string $jenis_unit
 * @property integer $lebar_unit
 * 
 * @method integer    getKodeJenisUnit()   Returns the current record's "kode_jenis_unit" value
 * @method string     getJenisUnit()       Returns the current record's "jenis_unit" value
 * @method integer    getLebarUnit()       Returns the current record's "lebar_unit" value
 * @method RJenisUnit setKodeJenisUnit()   Sets the current record's "kode_jenis_unit" value
 * @method RJenisUnit setJenisUnit()       Sets the current record's "jenis_unit" value
 * @method RJenisUnit setLebarUnit()       Sets the current record's "lebar_unit" value
 * 
 * @package    properti
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRJenisUnit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('r_jenis_unit');
        $this->hasColumn('kode_jenis_unit', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('jenis_unit', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('lebar_unit', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}