<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RSumberPembiayaan', 'doctrine');

/**
 * BaseRSumberPembiayaan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $kode_sumber_pembiayaan
 * @property string $sumber_pembiayaan
 * 
 * @method integer           getId()                     Returns the current record's "id" value
 * @method integer           getKodeSumberPembiayaan()   Returns the current record's "kode_sumber_pembiayaan" value
 * @method string            getSumberPembiayaan()       Returns the current record's "sumber_pembiayaan" value
 * @method RSumberPembiayaan setId()                     Sets the current record's "id" value
 * @method RSumberPembiayaan setKodeSumberPembiayaan()   Sets the current record's "kode_sumber_pembiayaan" value
 * @method RSumberPembiayaan setSumberPembiayaan()       Sets the current record's "sumber_pembiayaan" value
 * 
 * @package    properti
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRSumberPembiayaan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('r_sumber_pembiayaan');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('kode_sumber_pembiayaan', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('sumber_pembiayaan', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}