<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('TTower', 'doctrine');

/**
 * BaseTTower
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $kode_proyek
 * @property string $kode_tower
 * @property string $nama_tower
 * 
 * @method string getKodeProyek()  Returns the current record's "kode_proyek" value
 * @method string getKodeTower()   Returns the current record's "kode_tower" value
 * @method string getNamaTower()   Returns the current record's "nama_tower" value
 * @method TTower setKodeProyek()  Sets the current record's "kode_proyek" value
 * @method TTower setKodeTower()   Sets the current record's "kode_tower" value
 * @method TTower setNamaTower()   Sets the current record's "nama_tower" value
 * 
 * @package    properti
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTTower extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('t_tower');
        $this->hasColumn('kode_proyek', 'string', 2, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 2,
             ));
        $this->hasColumn('kode_tower', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('nama_tower', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}