<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RStatusUnit', 'doctrine');

/**
 * BaseRStatusUnit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $kode_status_unit
 * @property string $status_unit
 * @property string $kode_warna
 * 
 * @method integer     getKodeStatusUnit()   Returns the current record's "kode_status_unit" value
 * @method string      getStatusUnit()       Returns the current record's "status_unit" value
 * @method string      getKodeWarna()        Returns the current record's "kode_warna" value
 * @method RStatusUnit setKodeStatusUnit()   Sets the current record's "kode_status_unit" value
 * @method RStatusUnit setStatusUnit()       Sets the current record's "status_unit" value
 * @method RStatusUnit setKodeWarna()        Sets the current record's "kode_warna" value
 * 
 * @package    properti
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRStatusUnit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('r_status_unit');
        $this->hasColumn('kode_status_unit', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('status_unit', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 15,
             ));
        $this->hasColumn('kode_warna', 'string', 6, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 6,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}