<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RJenisKelamin', 'doctrine');

/**
 * BaseRJenisKelamin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $kode_jenis_kelamin
 * @property string $jenis_kelamin
 * 
 * @method integer       getId()                 Returns the current record's "id" value
 * @method string        getKodeJenisKelamin()   Returns the current record's "kode_jenis_kelamin" value
 * @method string        getJenisKelamin()       Returns the current record's "jenis_kelamin" value
 * @method RJenisKelamin setId()                 Sets the current record's "id" value
 * @method RJenisKelamin setKodeJenisKelamin()   Sets the current record's "kode_jenis_kelamin" value
 * @method RJenisKelamin setJenisKelamin()       Sets the current record's "jenis_kelamin" value
 * 
 * @package    properti
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRJenisKelamin extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('r_jenis_kelamin');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('kode_jenis_kelamin', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
        $this->hasColumn('jenis_kelamin', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}