<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RPekerjaan', 'doctrine');

/**
 * BaseRPekerjaan
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $kode_pekerjaan
 * @property string $pekerjaan
 * 
 * @method integer    getKodePekerjaan()  Returns the current record's "kode_pekerjaan" value
 * @method string     getPekerjaan()      Returns the current record's "pekerjaan" value
 * @method RPekerjaan setKodePekerjaan()  Sets the current record's "kode_pekerjaan" value
 * @method RPekerjaan setPekerjaan()      Sets the current record's "pekerjaan" value
 * 
 * @package    properti
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRPekerjaan extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('r_pekerjaan');
        $this->hasColumn('kode_pekerjaan', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pekerjaan', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}