<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RStatusLantai', 'doctrine');

/**
 * BaseRStatusLantai
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $kode_status_lantai
 * @property string $status_lantai
 * 
 * @method integer       getId()                 Returns the current record's "id" value
 * @method integer       getKodeStatusLantai()   Returns the current record's "kode_status_lantai" value
 * @method string        getStatusLantai()       Returns the current record's "status_lantai" value
 * @method RStatusLantai setId()                 Sets the current record's "id" value
 * @method RStatusLantai setKodeStatusLantai()   Sets the current record's "kode_status_lantai" value
 * @method RStatusLantai setStatusLantai()       Sets the current record's "status_lantai" value
 * 
 * @package    properti
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRStatusLantai extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('r_status_lantai');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('kode_status_lantai', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('status_lantai', 'string', 30, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 30,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}