# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        Adhi Persada Properti
    description:  Adhi Persada Properti
    keywords:     Adhi Persada Properti
    language:     id
    robots:       index, follow

  stylesheets:    
                  - main.css
                  - bootstrap.min.css
                  - navbar-fixed-top.css
                  - font-awesome.min.css

  javascripts:    
                  - html5shiv.min.js
                  - respond.min.js
                  - jquery.min.js
                  - bootstrap.min.js                  

  has_layout:     true
  layout:         layout
