<?php

/**
 * RCaraBayarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RCaraBayarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RCaraBayarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RCaraBayar');
    }
}