<?php

/**
 * RFasilitasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RFasilitasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RFasilitasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RFasilitas');
    }
}