<?php

/**
 * RJenisProyekTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RJenisProyekTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RJenisProyekTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RJenisProyek');
    }
}