<?php

/**
 * RJenisUnitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RJenisUnitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RJenisUnitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RJenisUnit');
    }
}