<?php

/**
 * RJenisKelaminTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RJenisKelaminTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RJenisKelaminTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RJenisKelamin');
    }
}