<?php

/**
 * RKartuIdentitasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RKartuIdentitasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RKartuIdentitasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RKartuIdentitas');
    }
}