<?php

/**
 * RPekerjaanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RPekerjaanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RPekerjaanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RPekerjaan');
    }
}