<?php

/**
 * RStatusUnitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RStatusUnitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RStatusUnitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RStatusUnit');
    }
}