<?php

/**
 * RStatusLantaiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RStatusLantaiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RStatusLantaiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RStatusLantai');
    }
}