<?php

/**
 * RStatusPesananTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RStatusPesananTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RStatusPesananTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RStatusPesanan');
    }
}