<?php

/**
 * RSumberInformasiTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RSumberInformasiTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RSumberInformasiTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RSumberInformasi');
    }
}