<?php

/**
 * RSumberPembiayaanTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RSumberPembiayaanTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RSumberPembiayaanTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RSumberPembiayaan');
    }
}