<?php

/**
 * RTujuanPembelianTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RTujuanPembelianTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RTujuanPembelianTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RTujuanPembelian');
    }
}