<?php

/**
 * TFasilitasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TFasilitasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TFasilitasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TFasilitas');
    }
}