<?php

/**
 * THargaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class THargaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object THargaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('THarga');
    }
}