<?php

/**
 * TKonsumenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TKonsumenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TKonsumenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TKonsumen');
    }
}