<?php

/**
 * TPesananTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TPesananTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TPesananTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TPesanan');
    }
}