<?php

/**
 * TProyekTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TProyekTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TProyekTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TProyek');
    }
}