<?php

/**
 * TRiwayatHargaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TRiwayatHargaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TRiwayatHargaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TRiwayatHarga');
    }
}