<?php

/**
 * TSalesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TSalesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TSalesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TSales');
    }
}