<?php

/**
 * TTowerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TTowerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TTowerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TTower');
    }
}