<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/10/09 23:57:10

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=karsain2_property',
  'username' => 'properti',
  'password' => '4m4n4h',
  'name' => 'doctrine',
)),);
