<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/10/09 23:57:10
sfConfig::add(array(
  'app_sf_guard_plugin_success_signin_url' => '@dashboard',
  'app_sf_guard_plugin_success_signout_url' => '@homepage',
));
