<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/10/09 23:57:01
sfConfig::add(array(
  'mod_sfguardpermission_enabled' => true,
  'mod_sfguardpermission_view_class' => 'sfPHP',
));
