<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/10/10 00:00:19
sfConfig::add(array(
  'app_sf_guard_plugin_success_signin_url' => '@homepage',
  'app_sf_guard_plugin_success_signout_url' => '@homepage',
));
