RCaraBayar:
  connection: doctrine
  tableName: r_cara_bayar
  columns:
    kode_cara_bayar:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    cara_bayar:
      type: string(10)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
RFasilitas:
  connection: doctrine
  tableName: r_fasilitas
  columns:
    kode_fasilitas:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    fasilitas:
      type: string(50)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
RJenisKelamin:
  connection: doctrine
  tableName: r_jenis_kelamin
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    kode_jenis_kelamin:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    jenis_kelamin:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
RJenisProyek:
  connection: doctrine
  tableName: r_jenis_proyek
  columns:
    kode_jenis_proyek:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    jenis_proyek:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
RJenisUnit:
  connection: doctrine
  tableName: r_jenis_unit
  columns:
    kode_jenis_unit:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    jenis_unit:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    lebar_unit:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
RKartuIdentitas:
  connection: doctrine
  tableName: r_kartu_identitas
  columns:
    kode_kartu_identitas:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    kartu_identitas:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
RPekerjaan:
  connection: doctrine
  tableName: r_pekerjaan
  columns:
    kode_pekerjaan:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    pekerjaan:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
RStatusKonsumen:
  connection: doctrine
  tableName: r_status_konsumen
  columns:
    kode_status_konsumen:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    status_konsumen:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
RStatusLantai:
  connection: doctrine
  tableName: r_status_lantai
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    kode_status_lantai:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    status_lantai:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
RStatusPesanan:
  connection: doctrine
  tableName: r_status_pesanan
  columns:
    kode_status_pesanan:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    status_pesanan:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
RStatusUnit:
  connection: doctrine
  tableName: r_status_unit
  columns:
    kode_status_unit:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    status_unit:
      type: string(15)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_warna:
      type: string(6)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
RSumberInformasi:
  connection: doctrine
  tableName: r_sumber_informasi
  columns:
    kode_sumber_informasi:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    sumber_informasi:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
RSumberPembiayaan:
  connection: doctrine
  tableName: r_sumber_pembiayaan
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    kode_sumber_pembiayaan:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    sumber_pembiayaan:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
RTujuanPembelian:
  connection: doctrine
  tableName: r_tujuan_pembelian
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    kode_tujuan_pembelian:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tujuan_pembelian:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
TFasilitas:
  connection: doctrine
  tableName: t_fasilitas
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    kode_proyek:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_fasilitas:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
THarga:
  connection: doctrine
  tableName: t_harga
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    kode_proyek:
      type: string(2)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_tower:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    type_unit:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    harga_unit:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    berlaku_mulai:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
TKonsumen:
  connection: doctrine
  tableName: t_konsumen
  columns:
    kode_status_konsumen:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_konsumen:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    nama_lengkap_konsumen:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tempat_lahir_konsumen:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tanggal_lahir_konsumen:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_jenis_kelamin:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_identitas:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    no_identitas:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nama_jalan:
      type: string(35)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    rt:
      type: string(3)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    rw:
      type: string(3)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_kelurahan:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_kecamatan:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_kabupaten:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_pos:
      type: string(5)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_propinsi:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_area:
      type: string(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    telpon_rumah:
      type: string(8)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    no_hp:
      type: string(15)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    no_hp2:
      type: string(15)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email1:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    email2:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_pekerjaan:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
TPembayaran:
  connection: doctrine
  tableName: t_pembayaran
  columns:
    kode_pembayaran:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    kode_pemesanan:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_cara_bayar:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tanggal_pembayaran:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    amount:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    no_referensi:
      type: string(30)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    approval_kasir:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tanggal_approval_kasir:
      type: timestamp(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    approval_manager_penjualan:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tanggal_approval_manager:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
TPesanan:
  connection: doctrine
  tableName: t_pesanan
  columns:
    status_pesanan:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_pesanan:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    kode_unit:
      type: string(7)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_konsumen:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_sales:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tanggal_pesan:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    list_price:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    discount:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    harga_kontrak:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_sumber_info:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_pembiayaan:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_tujuan_pembelian:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_event:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    tanggal_jatuh_tempo:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    status_pembayaran:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
TProyek:
  connection: doctrine
  tableName: t_proyek
  columns:
    kode_proyek:
      type: string(2)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    nama_proyek:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    jenis_proyek:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    nama_jalan:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_kelurahan:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_kecamatan:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_kabupaten_kota:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_pos:
      type: string(5)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_propinsi:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
TRiwayatHarga:
  connection: doctrine
  tableName: t_riwayat_harga
  columns:
    id:
      type: integer(8)
      autoincrement: true
      primary: true
    kode_proyek:
      type: string(2)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_tower:
      type: string(1)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    type_unit:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    harga_unit:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    berlaku_mulai:
      type: date(25)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
TSales:
  connection: doctrine
  tableName: t_sales
  columns:
    kode_sales:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    nama_sales:
      type: string()
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_unit_sales:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_atasan:
      type: integer(4)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
TTower:
  connection: doctrine
  tableName: t_tower
  columns:
    kode_proyek:
      type: string(2)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
    kode_tower:
      type: string(1)
      fixed: false
      unsigned: false
      primary: true
      autoincrement: false
    nama_tower:
      type: string(15)
      fixed: false
      unsigned: false
      primary: false
      notnull: true
      autoincrement: false
